FROM python:3.11-slim

WORKDIR /app

RUN pip install pydicom pynetdicom

RUN mkdir data
RUN mkdir data_received

COPY data ./data/
COPY client.py .
COPY storage_scp.py .

EXPOSE 11113
EXPOSE 11112

CMD ["python", "-u", "storage_scp.py"]